channels:
    - http://conda.ipd.uw.edu
    - anaconda
    - conda-forge
dependencies:
    - python
    - numpy
    - rif
    - pyrosetta
    - sphinx
    - docutils
    - numpy
    - pyyaml
    - pytest
    - pytest-cov
    - coverage
    - codecov
    - pytest-runner
    - h5py
    - cryptography
    - more-itertools
    - tox
    - watchdog
    - flake8
    - pip:
        - rmsd
