channels:
    - http://conda.ipd.uw.edu
    - anaconda
    - conda-forge
dependencies:
    - python
    - jupyter_console
    - numpy
    - dask
    # - zarr # NOTE(onalant): PR for shaped sub-dtypes here https://github.com/zarr-developers/zarr/pull/296
    - numcodecs
    - rif
    - pyrosetta
    - sphinx
    - docutils
    - numpy
    - pyyaml
    - pytest
    - pytest-cov
    - coverage
    - codecov
    - pytest-runner
    - cryptography
    - more-itertools
    - tox
    - watchdog
    - flake8
    - pip:
        - rmsd
        - git+https://github.com/onalant/zarr.git@shape
